import React from 'react';
import API from '../utils/API';
import DataBody from './DataBody';
import DataTable from './DataTable';
import Header from './Header';
import Nav from './Nav';
import SearchBox from './SearchBox';
import Wrapper from './Wrapper';
import DataArea from './DataArea';